using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Odyssey.Context.ModelConfiguration;

internal sealed class CurrencyConfiguration : IEntityTypeConfiguration<Currency>
{
    public void Configure(EntityTypeBuilder<Currency> entity)
    {
        entity.HasData(
            new Currency { CurrencyCode = "AED", Name = "UAE Dirham", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "AFN", Name = "Afghani", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "AMD", Name = "Armenian Dram", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "AOA", Name = "Kwanza", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "ARS", Name = "Argentine Peso", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "AUD", Name = "Australian Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "AWG", Name = "Aruban Florin", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "AZN", Name = "Azerbaijan Manat", MinorUnits = 2, Symbol = "₼", Archived = null },
            new Currency { CurrencyCode = "BAM", Name = "Convertible Mark", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BBD", Name = "Barbados Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "BDT", Name = "Taka", MinorUnits = 2, Symbol = "৳", Archived = null },
            new Currency { CurrencyCode = "BHD", Name = "Bahraini Dinar", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BIF", Name = "Burundi Franc", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BMD", Name = "Bermudian Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "BND", Name = "Brunei Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "BOB", Name = "Boliviano", MinorUnits = 2, Symbol = "Bs.", Archived = null },
            new Currency { CurrencyCode = "BOV", Name = "Mvdol", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BRL", Name = "Brazilian Real", MinorUnits = 2, Symbol = "R$", Archived = null },
            new Currency { CurrencyCode = "BSD", Name = "Bahamian Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "BTN", Name = "Ngultrum", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BWP", Name = "Pula", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BYN", Name = "Belarusian Ruble", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "BZD", Name = "Belize Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "CAD", Name = "Canadian Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "CDF", Name = "Congolese Franc", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "CHE", Name = "WIR Euro", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "CHF", Name = "Swiss Franc", MinorUnits = 2, Symbol = "CHF", Archived = null },
            new Currency { CurrencyCode = "CHW", Name = "WIR Franc", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "CLF", Name = "Unidad de Fomento", MinorUnits = 4, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "CLP", Name = "Chilean Peso", MinorUnits = 0, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "CNY", Name = "Yuan Renminbi", MinorUnits = 2, Symbol = "¥", Archived = null },
            new Currency { CurrencyCode = "COP", Name = "Colombian Peso", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "COU", Name = "Unidad de Valor Real", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "CRC", Name = "Costa Rican Colon", MinorUnits = 2, Symbol = "₡", Archived = null },
            new Currency { CurrencyCode = "CUP", Name = "Cuban Peso", MinorUnits = 2, Symbol = "₱", Archived = null },
            new Currency { CurrencyCode = "CVE", Name = "Cape Verde Escudo", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "CZK", Name = "Czech Koruna", MinorUnits = 2, Symbol = "Kč", Archived = null },
            new Currency { CurrencyCode = "DJF", Name = "Djibouti Franc", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "DKK", Name = "Danish Krone", MinorUnits = 2, Symbol = "kr", Archived = null },
            new Currency { CurrencyCode = "DOP", Name = "Dominican Peso", MinorUnits = 2, Symbol = "RD$", Archived = null },
            new Currency { CurrencyCode = "DZD", Name = "Algerian Dinar", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "EGP", Name = "Egyptian Pound", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "ERN", Name = "Nakfa", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "ETB", Name = "Ethiopian Birr", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "FJD", Name = "Fiji Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "FKP", Name = "Falkland Islands Pound", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "GBP", Name = "Pound Sterling", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "GEL", Name = "Lari", MinorUnits = 2, Symbol = "₾", Archived = null },
            new Currency { CurrencyCode = "GHS", Name = "Ghana Cedi", MinorUnits = 2, Symbol = "₵", Archived = null },
            new Currency { CurrencyCode = "GIP", Name = "Gibraltar Pound", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "GMD", Name = "Dalasi", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "GNF", Name = "Guinean Franc", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "GTQ", Name = "Quetzal", MinorUnits = 2, Symbol = "Q", Archived = null },
            new Currency { CurrencyCode = "GYD", Name = "Guyana Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "HKD", Name = "Hong Kong Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "HNL", Name = "Lempira", MinorUnits = 2, Symbol = "L", Archived = null },
            new Currency { CurrencyCode = "HTG", Name = "Gourde", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "HUF", Name = "Forint", MinorUnits = 2, Symbol = "Ft", Archived = null },
            new Currency { CurrencyCode = "IDR", Name = "Rupiah", MinorUnits = 2, Symbol = "Rp", Archived = null },
            new Currency { CurrencyCode = "ILS", Name = "New Israeli Sheqel", MinorUnits = 2, Symbol = "₪", Archived = null },
            new Currency { CurrencyCode = "INR", Name = "Indian Rupee", MinorUnits = 2, Symbol = "₹", Archived = null },
            new Currency { CurrencyCode = "IQD", Name = "Iraqi Dinar", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "IRR", Name = "Iranian Rial", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "ISK", Name = "Iceland Krona", MinorUnits = 0, Symbol = "kr", Archived = null },
            new Currency { CurrencyCode = "JMD", Name = "Jamaican Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "JOD", Name = "Jordanian Dinar", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "JPY", Name = "Yen", MinorUnits = 0, Symbol = "¥", Archived = null },
            new Currency { CurrencyCode = "KES", Name = "Kenyan Shilling", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "KGS", Name = "Som", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "KHR", Name = "Riel", MinorUnits = 2, Symbol = "៛", Archived = null },
            new Currency { CurrencyCode = "KMF", Name = "Comorian Franc", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "KPW", Name = "North Korean Won", MinorUnits = 0, Symbol = "₩", Archived = null },
            new Currency { CurrencyCode = "KRW", Name = "Won", MinorUnits = 0, Symbol = "₩", Archived = null },
            new Currency { CurrencyCode = "KWD", Name = "Kuwaiti Dinar", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "KYD", Name = "Cayman Islands Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "KZT", Name = "Tenge", MinorUnits = 2, Symbol = "₸", Archived = null },
            new Currency { CurrencyCode = "LAK", Name = "Lao Kip", MinorUnits = 0, Symbol = "₭", Archived = null },
            new Currency { CurrencyCode = "LBP", Name = "Lebanese Pound", MinorUnits = 0, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "LKR", Name = "Sri Lanka Rupee", MinorUnits = 2, Symbol = "₨", Archived = null },
            new Currency { CurrencyCode = "LRD", Name = "Liberian Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "LSL", Name = "Loti", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "LYD", Name = "Libyan Dinar", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MAD", Name = "Moroccan Dirham", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MDL", Name = "Moldovan Leu", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MGA", Name = "Malagasy Ariary", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MMK", Name = "Kyat", MinorUnits = 2, Symbol = "Ks", Archived = null },
            new Currency { CurrencyCode = "MNT", Name = "Tugrik", MinorUnits = 2, Symbol = "₮", Archived = null },
            new Currency { CurrencyCode = "MOP", Name = "Pataca", MinorUnits = 2, Symbol = "MOP$", Archived = null },
            new Currency { CurrencyCode = "MRU", Name = "Ouguiya", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MUR", Name = "Mauritius Rupee", MinorUnits = 2, Symbol = "₨", Archived = null },
            new Currency { CurrencyCode = "MVR", Name = "Rufiyaa", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MWK", Name = "Malawi Kwacha", MinorUnits = 2, Symbol = "MK", Archived = null },
            new Currency { CurrencyCode = "MXN", Name = "Mexican Peso", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "MXV", Name = "Mexican Unidad de Inversion (UDI)", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "MYR", Name = "Malaysian Ringgit", MinorUnits = 2, Symbol = "RM", Archived = null },
            new Currency { CurrencyCode = "MZN", Name = "Mozambique Metical", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "NAD", Name = "Namibia Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "NGN", Name = "Naira", MinorUnits = 2, Symbol = "₦", Archived = null },
            new Currency { CurrencyCode = "NIO", Name = "Cordoba Oro", MinorUnits = 2, Symbol = "C$", Archived = null },
            new Currency { CurrencyCode = "NOK", Name = "Norwegian Krone", MinorUnits = 2, Symbol = "kr", Archived = null },
            new Currency { CurrencyCode = "NPR", Name = "Nepalese Rupee", MinorUnits = 2, Symbol = "₨", Archived = null },
            new Currency { CurrencyCode = "NZD", Name = "New Zealand Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "OMR", Name = "Rial Omani", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "PAB", Name = "Balboa", MinorUnits = 2, Symbol = "B/.", Archived = null },
            new Currency { CurrencyCode = "PEN", Name = "Sol", MinorUnits = 2, Symbol = "S/", Archived = null },
            new Currency { CurrencyCode = "PGK", Name = "Kina", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "PHP", Name = "Philippine Peso", MinorUnits = 2, Symbol = "₱", Archived = null },
            new Currency { CurrencyCode = "PKR", Name = "Pakistan Rupee", MinorUnits = 2, Symbol = "₨", Archived = null },
            new Currency { CurrencyCode = "PLN", Name = "Zloty", MinorUnits = 2, Symbol = "zł", Archived = null },
            new Currency { CurrencyCode = "PYG", Name = "Guarani", MinorUnits = 0, Symbol = "₲", Archived = null },
            new Currency { CurrencyCode = "QAR", Name = "Qatari Rial", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "RON", Name = "Romanian Leu", MinorUnits = 2, Symbol = "lei", Archived = null },
            new Currency { CurrencyCode = "RSD", Name = "Serbian Dinar", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "RUB", Name = "Russian Ruble", MinorUnits = 2, Symbol = "₽", Archived = null },
            new Currency { CurrencyCode = "RWF", Name = "Rwanda Franc", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "SAR", Name = "Saudi Riyal", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "SBD", Name = "Solomon Islands Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "SCR", Name = "Seychelles Rupee", MinorUnits = 2, Symbol = "₨", Archived = null },
            new Currency { CurrencyCode = "SDG", Name = "Sudanese Pound", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "SEK", Name = "Swedish Krona", MinorUnits = 2, Symbol = "kr", Archived = null },
            new Currency { CurrencyCode = "SGD", Name = "Singapore Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "SHP", Name = "Saint Helena Pound", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "SLE", Name = "Leone", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "SOS", Name = "Somali Shilling", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "SRD", Name = "Surinam Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "SSP", Name = "South Sudanese Pound", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "STN", Name = "Dobra", MinorUnits = 2, Symbol = "Db", Archived = null },
            new Currency { CurrencyCode = "SVC", Name = "El Salvador Colon", MinorUnits = 2, Symbol = "₡", Archived = null },
            new Currency { CurrencyCode = "SYP", Name = "Syrian Pound", MinorUnits = 2, Symbol = "£", Archived = null },
            new Currency { CurrencyCode = "SZL", Name = "Lilangeni", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "THB", Name = "Baht", MinorUnits = 2, Symbol = "฿", Archived = null },
            new Currency { CurrencyCode = "TJS", Name = "Somoni", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "TMT", Name = "Turkmenistan New Manat", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "TND", Name = "Tunisian Dinar", MinorUnits = 3, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "TOP", Name = "Pa'anga", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "TRY", Name = "Turkish Lira", MinorUnits = 2, Symbol = "₺", Archived = null },
            new Currency { CurrencyCode = "TTD", Name = "Trinidad and Tobago Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "TWD", Name = "New Taiwan Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "TZS", Name = "Tanzanian Shilling", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "UGX", Name = "Uganda Shilling", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "USD", Name = "US Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "USN", Name = "US Dollar (Next Day)", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "UYI", Name = "Uruguay Peso en Unidades Indexadas (UI)", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "UYU", Name = "Peso Uruguayo", MinorUnits = 2, Symbol = "$U", Archived = null },
            new Currency { CurrencyCode = "UYW", Name = "Unidad Previsional", MinorUnits = 4, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "UZS", Name = "Uzbekistan Sum", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "VED", Name = "Bolivar Digital", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "VND", Name = "Dong", MinorUnits = 0, Symbol = "₫", Archived = null },
            new Currency { CurrencyCode = "VUV", Name = "Vatu", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "WST", Name = "Tala", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "XAF", Name = "CFA Franc BEAC", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "XCD", Name = "East Caribbean Dollar", MinorUnits = 2, Symbol = "$", Archived = null },
            new Currency { CurrencyCode = "XCG", Name = "Caribbean Guilder", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "XOF", Name = "CFA Franc BCEAO", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "XPF", Name = "CFP Franc", MinorUnits = 0, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "YER", Name = "Yemeni Rial", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "ZAR", Name = "Rand", MinorUnits = 2, Symbol = "R", Archived = null },
            new Currency { CurrencyCode = "ZMW", Name = "Zambian Kwacha", MinorUnits = 2, Symbol = "ZK", Archived = null },
            new Currency { CurrencyCode = "ZWG", Name = "Zimbabwe Gold", MinorUnits = 2, Symbol = null, Archived = null },
            new Currency { CurrencyCode = "EUR", Name = "Euro", MinorUnits = 2, Symbol = "€", Archived = null },
            new Currency { CurrencyCode = "BGN", Name = "Bulgarian Lev", MinorUnits = 2, Symbol = "лв", Archived = null },
            new Currency { CurrencyCode = "MKD", Name = "Macedonian Denar", MinorUnits = 2, Symbol = "ден", Archived = null },
            new Currency { CurrencyCode = "ALL", Name = "Albanian Lek", MinorUnits = 2, Symbol = "L", Archived = null },
            new Currency { CurrencyCode = "UAH", Name = "Ukrainian Hryvnia", MinorUnits = 2, Symbol = "₴", Archived = null }
        );
    }
}
